#implementing POP operation subject to exception in python
stack = []
stack.append('1')
stack.append('2')
stack.append('3')
try:
    raise IndexError
except Exception as e:
    excepName = type(e)._name_
print('Initial stack')
print(stack)
print('\nElements poped from stack:')
print(stack.pop(1))
print(stack)
output:
Initial stack
['1', '2', '3']

Elements poped from stack:
2
['1', '3']
